//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exam
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class exambdEntities_new : DbContext
    {
        public exambdEntities_new()
            : base("name=exambdEntities_new")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bllood> bllood { get; set; }
        public virtual DbSet<patients> patients { get; set; }
        public virtual DbSet<services> services { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
