//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class services
    {
        public int Code { get; set; }
        public string Service { get; set; }
        public string Price { get; set; }
    }
}
